[workspace]
resolver = "2"
members = [
  "programs/audit_registry"
]

[workspace.dependencies]
anchor-lang = { version = "0.29.0" }
solana-program = { version = "1.17.15" }

[profile.release]
overflow-checks = true

