[workspace]
resolver = "2"
members = [
  "programs/audit_registry"
]

[workspace.dependencies]
anchor-lang = { version = "0.30.1" }

[profile.release]
overflow-checks = true

[patch.crates-io]
anchor-syn = { path = "../vendor/anchor-syn" }

